### ISSUE TITLE
Dosn't work on android (or just nexus?)

### ISSUE THREAD

**Issue by jimmywarting** [technoboy10/crossorigin.me#10]
I have a samsung galaxy s4 with custom rom "google play edition" and a nexus 9 
all request returns 404

and the same request works fine on iphone & mac on the same network

Perhaps androids fault that it can't parse the url properly?

sample req: GET http://crossorigin.me/http://ifconfig.me

**Comment by technoboy10** [comment]
Seems to work fine on my OnePlus One (running Lollipop). Maybe try again?

**Comment by jimmywarting** [comment]
Nope, the error i get is with a / in the beginning

Got the error: Not Found
while trying to obtain /http://ifconfig.me

**Comment by technoboy10** [comment]
Are you still getting the error?

**Comment by jimmywarting** [comment]
Still says
>Got the error: Not Found
while trying to obtain /http://ifconfig.me

**Comment by technoboy10** [comment]
Does the error happen on other sites? I've noticed weird bugs with ifconfig.me, so that might be unrelated.

**Comment by jimmywarting** [comment]
Yes...
![screenshot_2015-11-14-01-48-38](https://cloud.githubusercontent.com/assets/1148376/11160945/0a20a2ea-8a72-11e5-8f60-a431dd97ef31.png)

**Comment by jimmywarting** [comment]
hmm, if i switched of "Data saver" then i was able to reproduce the error.
If the Data saver was on it would go to googles server and fetch it properly.

Could perhaps be my own network / router that is spooking me? so i tried another wifi and also 4g network with "Data saver" turned off, same error

**Comment by schme16** [comment]
@jimmywarting: I've tested with my Nexus 5, Nexus , and my LG G3, on both a home and corporate network, and with both internal webpages and external, mostly to the same effect: Only in Chrome and only when data saver was *on* did the site fail to load.

Have you been able to try this out on a 3/4G network or corporate network to check if it's your home network getting spooked?

**Comment by jimmywarting** [comment]
I tried both.  It has nothing to with my network

**Comment by schme16** [comment]
@jimmywarting: dang, I am fresh out of ideas! I'll keep looking into it, maybe I'll stumble on some arcane webkit thing that will help resolve this (sorry :( )

**Comment by tjvr** [comment]
I wonder if this was caused by #18...

**Comment by jimmywarting** [comment]
Seems to work now...
