### ISSUE TITLE
Support caching

### ISSUE THREAD

**Issue by emnh** [technoboy10/crossorigin.me#11]
Support browser caching by forwarding the appropriate headers

**Comment by BernieSumption** [comment]
I created a pull request a few weeks ago that did exactly this, and improved streaming performance. I've had no response so far, I'm wondering if the maintainer saw it? I can't find any contact details for him.

https://github.com/technoboy10/crossorigin.me/pull/7

**Comment by emnh** [comment]
@BernieSumption Yes, thanks :) . Your pull request seems to have merge conflicts now though.

I forked your fork and hacked a quick workaround for sites not supporting caching plus some other changes.

I was wondering, don't you need to add all the cache headers to Access-Control-Allow-Headers?

res.setHeader('Access-Control-Allow-Headers', 'Content-Type,If-None-Match,If-Modified-Since,' + copyHeaders.join());

**Comment by emnh** [comment]
I also copy the client cache headers to the server, not just server cache headers to the client.

**Comment by BernieSumption** [comment]
> I was wondering, don't you need to add all the cache headers to Access-Control-Allow-Headers?

No - Access-Control-Allow-Headers affects the headers that the browser is allowed to send to the server, the server can respond with whatever headers it likes.

**Comment by emnh** [comment]
The client may want to send If-Modified-Since or If-None-Match, then the server responds with 304 Not Modified.

http://stackoverflow.com/questions/20978189/how-304-not-modified-works:

"When the browser puts something in its cache, it also stores the Last-Modified or ETag header from the server.

The browser then sends a request with the If-Modified-Since or If-None-Match header, telling the server to send a 304 if the content still has that date or ETag."

**Comment by BernieSumption** [comment]
Sure, your patch needs to set the Access-Control-Allow-Headers so that it can receive If-Modified-Since. My patch only affected the headers sent from the server to the client, so the ` + copyHeaders.join()` bit isn't required.

Also, as far as I can tell, your code sends the client's "If-Modified-Since" header to the upstream server as a "Date" header :o) (line 74)

> and hacked a quick workaround for sites not supporting caching plus some other changes.

My PR already does this. It defaults the "Expires" header to one day in the future. What change did you make along these lines?

**Comment by emnh** [comment]
Ah.. thanks for spotting that bug :)

I got bored with figuring out why the server wouldn't send a 304 and wanted to get back to programming my game, so if the client sends an If-modified-since at all, I send back a 304 and do not contact the server. I still don't get a 304 from the server though after fixing that bug, so I need to keep my hack for the time being.. It doesn't even work if I set Last-Modified in the future, so I guess the server just doesn't support If-Modified-Since. 

I set Last-Modified in client response to Date header from the server.

**Comment by technoboy10** [comment]
Sorry for the delayed response, I'll have some time to look over the patches this weekend. (by the way, you can contact me on Twitter at @technoboyIO)



—

**Comment by BernieSumption** [comment]
Thanks :o)

**Comment by technoboy10** [comment]
Merged. :)
