### ISSUE TITLE
No Access-Control-Allow-Origin header

### ISSUE THREAD

**Issue by PaquitoSoft** [technoboy10/crossorigin.me#12]
Hello,

First of all, thank you very much for having this service up and running.

I was using crossorigin.me for one tutorial I'm writing involving podcasts information and I discovered thant when I'm issuing request to one specific domain, the response does not include the expected Access-Control-Allow-Origin.

I found this problem with request to **www.npr.org** domain.

Here is a short list of podcasts feed URLs I'm having problems with:
```
 http://crossorigin.me/http://www.npr.org/rss/podcast.php?id=272112020
 http://crossorigin.me/http://www.npr.org/rss/podcast.php?id=510292
 http://crossorigin.me/http://www.npr.org/rss/podcast.php?id=510306
```

These are other podcasts feed URLs that show no problem:
```
http://crossorigin.me/http://feeds.feedburner.com/tiestos_club_life
http://crossorigin.me/http://static.aboveandbeyond.nu/grouptherapy/podcast.xml
http://crossorigin.me/http://songexploder.libsyn.com/rss	
```

Any idea about why the lack of the expected header?

Thanks.

**Comment by matthewbauer** [comment]
Looks like those URLs already have CORS enabled. Crossorigin.me is not adding Access-Control-Allow-Origin. Definitely a bug.

**Comment by PaquitoSoft** [comment]
I guess the problem is that you're deleting original headers and, as those URLs come from a server which already send the access-control-allow* headers, you're deleting legitimate ones.

I think there are two options:
* You can add "Access-Control-Allow-Origin" to the **copyHeaders** arrays (or [all the Access-Control-Allow-* header names](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#The_HTTP_response_headers))
* You can have a regexp to control which headers you delete from the original response so you don't remove the Access-Control-Allow-* ones.

Hope this can help.

Thanks!

**Comment by technoboy10** [comment]
Will work on fixing this within the next week or two.

**Comment by PaquitoSoft** [comment]
I've just created a pull request for you to take a look and merge it if you agree with it to solve this issue:
https://github.com/technoboy10/crossorigin.me/pull/13

**Comment by technoboy10** [comment]
@PaquitoSoft Merged.
