### ISSUE TITLE
Enable HTTPS

### ISSUE THREAD

**Issue by mathiasbynens** [technoboy10/crossorigin.me#14]
Please make crossorigin.me available over HTTPS!

This way it can be used in HTTPS pages without triggering mixed content errors.

At the moment, the easiest way to do this for free is to enable Cloudflare (takes 5 minutes). Soon, you’ll be able to use [Let’s Encrypt](https://letsencrypt.org/).

**Comment by grgarside** [comment]
You can use the Heroku URL which meets the *.herokuapp.com host name in the certificate:

- https://atcors.herokuapp.com/

**Comment by technoboy10** [comment]
I've set up CloudFlare on the domain. Everything should be https in a day or two.

**Comment by mathiasbynens** [comment]
It’s working: https://crossorigin.me/ Thanks!

Now all that remains is the CoinWallet thing mentioned in #15.
