### ISSUE TITLE
Error: Error: Invalid URI "%E2%80%8Bhttps://%E2%80%8Bgoogle.com"

### ISSUE THREAD

**Issue by joacim-boive** [technoboy10/crossorigin.me#18]
https://​crossorigin.me/​https://​google.com
Doesn't seem to be working anymore.

Tested in Chrome 46 and Safari 9.0.1

**Comment by technoboy10** [comment]
Not sure how to categorize this one - it looks like you've included a Unicode zero width space character (E2 80 8B) after the slashes. Did you copy and paste the URL from somewhere? Might be a bug, not sure.

**Comment by joacim-boive** [comment]
It's copy pasted from your page: =)
https://crossorigin.me

But thanks for your quick reply! Manually typing the URL worked perfectly,

**Comment by technoboy10** [comment]
As it turns out, the source did indeed have random zero width chars. Thanks for filing this! :)
