### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by schme16** [technoboy10/crossorigin.me#22]
@technoboy10: I was thinking that a small test suite (maybe written in [Mocha](https://mochajs.org/)) would be good to ensure that bugs and regressions don't creep in over time; depending on how into the idea you are, you (or I, if you're not sure how) could set up something like [Travis CI](https://travis-ci.org/) or [Wercker](http://wercker.com/) for auto-builds on commit/PRs; they both intergrate with 
GitHub and let you know if a commit/PR is broken, and won't allow merging until it's been fixed, which is great!

I'm happy to sketch a few tests out and make a PR if that would help illustrate the idea, your thoughts?

**Comment by technoboy10** [comment]
I've been meaning to do something like this for a while now - I'd love to see any ideas you have.

**Comment by technoboy10** [comment]
Closing as I'll probably deal with this early on with v2.
