### ISSUE TITLE
IE9

### ISSUE THREAD

**Issue by plonko** [technoboy10/crossorigin.me#25]
Has anyone tried using this in Internet Explorer 9 and made it work?
tanks

**Comment by liam4** [comment]
There's no frontend stuff so I highly doubt it wouldn't work on Interwebz Exploder 9, unless IE doesn't support some basic HTTP headers..

**Comment by plonko** [comment]
@liam4 Yeah it doesn't! :) http://stackoverflow.com/a/10232313/662826

**Comment by liam4** [comment]
Yuck, IE 9 is worse than I thought.. I'm not sure if it'd work, then. I'm on a Mac so I'm not really able to test.

**Comment by schme16** [comment]
@liam4 @plonko: I've run up against this issue a few times (until my employer finally updated IE to 11 as it's minimum delivery target); IE9 (and 8) do support CORS, but not from standard XMLHttpRequests, instead they're only support on the proprietary [XDomainRequest](https://developer.mozilla.org/en-US/docs/Web/API/XDomainRequest) method, it is, luckily, mostly the same.

**Comment by ManarKamel** [comment]
@plonko IE9 and IE8 support CORS, But not with jQuery Ajax or XMLHttpRequest, But with XDomainRequest, like @schme16  mentioned

```javascript
var XDR = new XDomainRequest();
XDR.onload = function () {
    var data = XDR.responseText;
    // Data processing                               
};
XDR.onerror = function () {
    console.log('error')
}
XDR.open('GET', url, true);
XDR.send();
```

You could check for support for XMLHttpRequest and XDomainRequest then send requests,
or you could put XDR in jQuery Ajax error function with checking support for XDR first of course

**Comment by technoboy10** [comment]
I'm not terribly concerned with supporting IE versions that aren't up to spec, so this isn't a high-priority issue.
