### ISSUE TITLE
Why is Access-Control-Allow in allowedOriginalHeaders.json?

### ISSUE THREAD

**Issue by metaodi** [technoboy10/crossorigin.me#26]
This leads to the strange situation, where a source already sets a  `Access-Control-Allow-Origin` header (e.g. to mydomain.com) and the proxy adds the `Access-Control-Allow-Origin: *`. This is something most browsers do not support and therefore the request fails.

I think the `Access-Control-Allow*` headers that the proxy sets, should not be passed through from the original source. WDYT?
##

**Comment by metaodi** [comment]
I see this change was introduced here: 6d80c3ace865bdeca7295b5abe6a802f8f38d43c by @PaquitoSoft. Maybe he can elaborate why this change is necessary/important.

I think the whole point of a CORS proxy is to make things easily accessible, that are otherwise not.

**Comment by PaquitoSoft** [comment]
@metaodi Did you check the issue where we discussed that modification? https://github.com/technoboy10/crossorigin.me/issues/12
The whole point was to reuse the original header if it already exists.
If there is an error in that commit, maybe you can send a pull request to fix it.

Regards.

**Comment by schme16** [comment]
@PaquitoSoft @metaodi: As of this PR: https://github.com/technoboy10/crossorigin.me/pull/21 there is the ability for a config parameter to be added; you could have the ability to ignore this header as an option.

eg: https://crossorigin.me/[Access-Control-Allow-Origin:false]http://example.com

It would require a PR to add this to the list of whitelisted options, and the little bit of glue logic to make it perform its intended purpose

**Comment by metaodi** [comment]
@PaquitoSoft Thanks for the pointer to the correct PR, yes I see it makes sense in some cases, in others (like mine) it doesn't.

@schme16 Thanks for this hint. I'm happy to create PR, maybe I have some time over the holidays to do that.

**Comment by technoboy10** [comment]
Closing since this is no longer relevant.
