### ISSUE TITLE
not working for google places

### ISSUE THREAD

**Issue by camilodelvasto** [technoboy10/crossorigin.me#29]
Just tried to circumvent cross origin request issues using the service but it doesn't seem to work. Somewhere I read that it is because Google won't serve data under http, but https... is there a way to fix that? Thanks!

**Comment by technoboy10** [comment]
If it's an http vs https issue, you should be able to just use `https://crossorigin.me/https://whatever`.

**Comment by camilodelvasto** [comment]
Sorry for the delay in the response. Haven't tried on Google Places but worked for me wonders on Wikipedia, so thanks and sorry for the dumb question! (hope this comment won't re-open the issue)
