### ISSUE TITLE
Restrict size of responses

### ISSUE THREAD

**Issue by technoboy10** [technoboy10/crossorigin.me#31]
Several people have been overusing/abusing the service by downloading >1MB files every second, leading to a 6TB bandwidth usage in January. I'm thinking that the best way to deal with this is to restrict the size of files passed through the proxy (which might also help prevent pirating uses of the proxy, which I don't want).

However, I have no clue how to code this restriction - anyone have any ideas?

**Comment by liam4** [comment]
And/or maybe limit the amount of data that can be retrieved from a single IP address (or possibly IPs that are in approximately the same location?) in 10 minutes (or an hour, or whatever)?

Preventing large responses shouldn't be tooooo hard, maybe kill the connection (or just stop receiving data) when the response size is too large?

**Comment by liam4** [comment]
Is this resolved?

**Comment by technoboy10** [comment]
Yeah.
