### ISSUE TITLE
service down

### ISSUE THREAD

**Issue by santiblanko** [technoboy10/crossorigin.me#35]
the service is down!

**Comment by technoboy10** [comment]
Restarted, and working on trying to figure out why it's doing this.

**Comment by santiblanko** [comment]
@technoboy10 Thank you for your help. But I can´t see the difference. It´s down now.
This morning at 7:00 am (Colombian hour) it´s up the service. DDOS?

**Comment by technoboy10** [comment]
Back up again. Looks like something is going weird with the Digital Ocean droplet. I'm investigating what the cause might be.

**Comment by grenade** [comment]
seems to be down today again

**Comment by technoboy10** [comment]
Got DDoSed. Working on making everything work again.
