### ISSUE TITLE
* wildcard and credentials flag

### ISSUE THREAD

**Issue by neojski** [technoboy10/crossorigin.me#4]
I wanted to use your http://crossorigin.me thingy with my [couchdb revision tree visualizer](https://github.com/neojski/visualizeRevTree). However, pouchdb shows the following error:

> XMLHttpRequest cannot load http://crossorigin.me/daleharvey.iriscouch.com/grocery/?_nonce=1430764622203. A wildcard '*' cannot be used in the 'Access-Control-Allow-Origin' header when the credentials flag is true. Origin 'http://localhost:8000' is therefore not allowed access.

Maybe you want to use some more advanced [cors proxy](https://github.com/gr2m/CORS-Proxy) that includes all the necessary headers?

**Comment by technoboy10** [comment]
Make sure that you use the full URL that you're accessing, including the "http://" bit, first of all. I've now set the credentials flag to false, which should fix that error for you. Let me know if it's still broken. :)


(btw, the reason I'm not using some other proxy is that crossorigin.me is largely a learning experience for me - figuring out how to build something like this from scratch)

**Comment by neojski** [comment]
It seems to be working now, thanks.

**Comment by neojski** [comment]
Nope, I was mistaken. I still get this error:

```
XMLHttpRequest cannot load http://crossorigin.me/http://daleharvey.iriscouch.com/grocery/?_nonce=1433254582212. A wildcard '*' cannot be used in the 'Access-Control-Allow-Origin' header when the credentials flag is true. Origin 'http://neojski.github.io' is therefore not allowed access.```

The headers that work:

```
Access-Control-Allow-Headers: accept, accept-charset, accept-encoding, accept-language, authorization, content-length, content-type, host, origin, proxy-connection, referer, user-agent, x-requested-with
Access-Control-Allow-Methods: HEAD, POST, GET, PUT, PATCH, DELETE
Access-Control-Allow-Origin: *
Access-Control-Max-Age: 86400
Cache-Control: must-revalidate
Connection: Keep-Alive
Content-Encoding: gzip
Content-Length: 181
Content-Type: text/plain; charset=utf-8
Date: Tue, 02 Jun 2015 14:17:50 GMT
Keep-Alive: timeout=15, max=100
Server: CouchDB/1.5.0 (Erlang OTP/R15B03)
Vary: Accept-Encoding
access-control-allow-credentials: true
```

Headers returned here:
```
Access-Control-Allow-Headers: Content-Type
Access-Control-Allow-Origin: *
Connection: keep-alive
Date: Tue, 02 Jun 2015 14:17:35 GMT
Server: Cowboy
Transfer-Encoding: chunked
Via: 1.1 vegur
access-control-allow-credentials: false
```

I'm not really sure why this does not work.
