### ISSUE TITLE
The Service Seems Down

### ISSUE THREAD

**Issue by kutec** [technoboy10/crossorigin.me#41]
Hi I am trying to implement the functionality where I need to fix crossorigin issue. I found crossorigin.me useful in this category. But the site is giving below error.

Error 522 Ray ID: 2938b7d5a0fb2ddf • 2016-04-14 17:01:24 UTC
Connection timed out

Could you please intimate? Also share the up time so that I can make a decision whether to consider for app or not.

Thanks.

**Comment by christophwolff** [comment]
+1

**Comment by demobox** [comment]
Also down from `213.139.137.6`

**Comment by technoboy10** [comment]
Thanks for letting me know. Looks like there's some kind of memory leak in the code, which is making the DO droplet crash. Working on fixing it, but there's probably going to be quite a bit of downtime in the next few days as I try and fix the problem.

**Comment by technoboy10** [comment]
Should be far more stable now. Going to create a new issue about the memory issue.

**Comment by demobox** [comment]
> Working on fixing it

Many thanks for taking a look at this, @technoboy10!

**Comment by demobox** [comment]
@technoboy10 Service seems to be down again..?

**Comment by kutec** [comment]
Still down for me!

**Comment by technoboy10** [comment]
Still dealing with memory leaks. 😞 

Another temporary fix in place.

**Comment by demobox** [comment]
> Still dealing with memory leak

Thanks for the update...good luck, and many thanks for continuing to taking a look at this!

**Comment by schme16** [comment]
@technoboy10: silly question, but are you settings the environmental variable `NODE_ENV` to 'production'? I've had all sorts of weird memory leaks with the http/https modules when I've forgotten to set it.

**Comment by technoboy10** [comment]
@schme16 The sillier thing is that you're right - I totally forgot to do that! Thanks for the help. :D

**Comment by schme16** [comment]
@technoboy10: Haha, I just hope that it turns out to be something so simple!
Occasionally I've had to do manual garbage collection by starting the node process with the `--always-compact --max_old_space_size=60  --nouse-idle-notification --expose-gc` flags and calling `global.gc();` in a `setTimeout` set for 5 minutes (or whatever)- but it's a yucky road to have to go down...
