### ISSUE TITLE
Production server sending 'random' 520 errors

### ISSUE THREAD

**Issue by technoboy10** [technoboy10/crossorigin.me#46]
Can't replicate on local copy, possibly some sort of caching bug related to cloudflare?

Affected URLs:
- http://quotes.stormconsultancy.co.uk/random.json
- http://www.ctabustracker.com/bustime/api/v1/getpredictions

**Comment by liam4** [comment]
I don't get an error on any of those links (using crossorigin.me).

**Comment by schme16** [comment]
I've not been able to repro this either...
It's possible that you're correct about it being a cloudflare issue.

Do you have any DO logs from when this was more frequently occurring?

**Comment by agouriou** [comment]
Hi,
First, thanks for this really useful project.

On to the bug, same issue right now with `https://crossorigin.me/https://google.com`

The result is a 520 error from Cloudflare.

Message from cloudflare:

> There is an issue between CloudFlare's cache and your origin web server. CloudFlare monitors for these errors and automatically investigates the cause. To help support the investigation, you can pull the corresponding error log from your web server and submit it our support team. Please include the Ray ID (which is at the bottom of this error page).

Here is the Ray ID:
`Ray ID: 2abac6cfd0913c65 • 2016-05-31 13:30:04 UTC`

**Comment by technoboy10** [comment]
I haven't seen any new reports of this in a while, so I'm going to close the issue.
