### ISSUE TITLE
Site down

### ISSUE THREAD

**Issue by walles** [technoboy10/crossorigin.me#49]
Hi!

When I browse to https://crossorigin.me I get:
```
Error 521 Ray ID: 2ac87d989b7316ac • 2016-06-02 05:26:28 UTC
Web server is down
```

Could you have a look at it please?

  Regards /Johan

**Comment by liam4** [comment]
Site works for me.

**Comment by technoboy10** [comment]
Hi @walles! The server isn't super stable right now, so I'm looking into better solutions for load balancing.  Sorry for any inconvenience!

**Comment by technoboy10** [comment]
Added load balancing, this should be fixed now.

**Comment by walles** [comment]
Seems to work [a lot better now](https://walles.github.io/weatherclock/), thanks @technoboy10.

Thanks for this service BTW, it's awesome!
