### ISSUE TITLE
MP4 error

### ISSUE THREAD

**Issue by herohamp** [technoboy10/crossorigin.me#52]
In this video after 11 seconds it pauses every time. I think it is an issue with crossorigin. https://crossorigin.me/https://r1---sn-8xgp1vo-p5q6.googlevideo.com/videoplayback?ratebypass=yes&pfa=5&itag=22&cnr=14&mime=video/mp4&initcwndbps=2015000&sver=3&fexp=3300116,3300132,3300164,3311881,3312144,3312381,3312725,3313263,9416126,9416891,9419451,9422596,9422844,9428398,9429743,9431012,9433096,9433380,9433946,9435526,9435580,9435681,9435876,9436588,9437066,9437164,9437553,9437679,9437742,9438337,9438768,9438974,9439356,9439581,9439652,9439853,9440168&ipbits=0&source=youtube&signature=87B14C817E2CE3432F6962619125217BB9F0680B.89D4487267969DE0A69391C11957A909638D240C&ctier=A&mt=1466814920&requiressl=yes&ms=au&mv=m&hightc=yes&pl=16&dur=247.664&lmt=1466769810651137&ip=96.255.116.80&id=o-AC4k_3w7AyuAtz1IBrqz_ovhTaDEBMwC8nPUdYpD-i4W&mn=sn-8xgp1vo-p5q6&mm=31&key=yt6&upn=HTrmbdIV6kw&expire=1466836681&sparams=cnr,ctier,dur,hightc,id,initcwndbps,ip,ipbits,itag,lmt,mime,mm,mn,ms,mv,pfa,pl,ratebypass,requiressl,source,upn,expire&title=A%20Mother%27s%20Overbearing%20Love

**Comment by technoboy10** [comment]
@herohamp This is likely due to the video file being larger than 2MB - after transferring 2MB of data, the server stops sending data to you.

**Comment by herohamp** [comment]
oh ok
