### ISSUE TITLE
allow encoding (base64?)

### ISSUE THREAD

**Issue by towc** [technoboy10/crossorigin.me#59]
It would be great if the users had the ability to bypass normal filters that check for specific patterns in the url, like "twitter.com", and this can be done in many ways

### base64
say that after `https://crossorigin.me/` we had something like `b64:aHR0cHM6Ly90d2l0dGVyLmNvbQ==`, that will evaluate to `https://twitter.com`, and the user can easily get it with `btoa('https://twitter.com')`

### rot13
add a rot13 function for the users to call in the console (rather than explicitly in the page), so they can just rotate the characters and put the output of `rot13('twitter.com:443')` in `https://crossorigin.me/r13:`

### polymorphic function
that changes every day or so, this way the url can't be checked easily, and you'd provide a function like rot13 that the user can look for in the JS code or by enumerating global variables

**Comment by technoboy10** [comment]
Can you describe a specific use case for these?

**Comment by towc** [comment]
The idea behind crossorigin.me is to get past the "cross-origin" bottleneck. Why not go all the way, and make it so that networks that disallow patterns like imgur to be in the requested url can still let it through?

**Comment by technoboy10** [comment]
This seems rather out of scope for the purpose of the proxy, and would likely get me in trouble with schools (which is problematic since crossorigin.me is used in an AP CS Principles curriculum).

**Comment by liam4** [comment]
If [redirectatob](http://redirectatob.github.io/) were server-based..
