### ISSUE TITLE
Add option to get real user ip address

### ISSUE THREAD

**Issue by ddsuresh** [technoboy10/crossorigin.me#61]
Right now it is giving crossorigin.me server ip in remote ip address, it will be useful if there is way to get real user's ip address.

**Comment by technoboy10** [comment]
Any specific use case? I'm hesitant to implement this as it reveals a lot of personal information.

**Comment by ddsuresh** [comment]
I am not sure what could be the problem in getting user's ip address. Normally we get these information in php when some access the website. But in my case, i am getting your server ip instead of the user who is accessing the url.

I have created tracking code and it will display a number based on IP, due to missing user's IP address, not able to generate different number based on IP address, it is always showing same number.

**Comment by technoboy10** [comment]
After discussing with some others, there's not really any good way to do this from my end. I recommend capturing the IP address yourself (some methods of doing this can be found in this [SO answer](http://stackoverflow.com/questions/391979/how-to-get-clients-ip-address-using-javascript-only)).
