### ISSUE TITLE
Query parameters being stripped

### ISSUE THREAD

**Issue by ping** [technoboy10/crossorigin.me#70]
This can be tested by a codepen from #50 http://codepen.io/anon/pen/JKKaZV

A request to http://api.forismatic.com/api/1.0/?lang=en&method=getQuote&format=json is stripped of its query params and becomes http://api.forismatic.com/api/1.0/ from crossorigin.

**Comment by zd333** [comment]
The same with me.

**Comment by eXaminator** [comment]
I also seem to have this problem.

**Comment by fega** [comment]
the same problem here.

**Comment by tjvr** [comment]
Duplicate of #76.
