### ISSUE TITLE
hstspreload.org multiple issues

### ISSUE THREAD

**Issue by galeksandrp** [technoboy10/crossorigin.me#74]
* 403 Origin: header is required
* XMLHttpRequest cannot load https://crossorigin.me/https://hstspreload.org/api/v2/status?domain=hashicorp.com. The 'Access-Control-Allow-Origin' header contains multiple values '*, null', but only one is allowed. Origin 'https://fiddle.jshell.net' is therefore not allowed access.

Similar #73 #71

**Comment by tjvr** [comment]
This issue is a duplicate. @technoboy10

**Comment by technoboy10** [comment]
Duplicate of #73.
