### ISSUE TITLE
Query strings not working

### ISSUE THREAD

**Issue by technoboy10** [technoboy10/crossorigin.me#76]
As several people have pointed out, query strings are not working properly in the v2 preview. Need to figure out how to import all query strings from restify. Bummer that this is an issue.

**Comment by n1k0** [comment]
Funnily enough master works just fine with query strings when running the proxy locally. May the issue due with the version deployed to `https://crossorigin.me/`?

**Comment by technoboy10** [comment]
Yes, it's an issue with Restify, which is the basis of v2.

[Connor Hudson - Contact Using Hop](http://GetHop.com/?_hmid=1483290889)

On January 1, 2017 at 14:58 GMT, Nicolas Perriault <notifications@github.com> wrote:

Funnily enough master works just fine with query strings when running the proxy locally. May the issue due with the version deployed to https://crossorigin.me/?

**Comment by technoboy10** [comment]
Fixed via 6ac11f79b7944b74c64fe3584da7fcb036a21272.
