### ISSUE TITLE
Need to set custom headers

### ISSUE THREAD

**Issue by jimmywarting** [technoboy10/crossorigin.me#78]
I have a api where i need to include one cookie to get the result
I don't need to know any users credentials it's just if this is missing then the request won't work

https://secure.dplay.se/secure/api/v2/user/authorization/stream/184471
Cookie: dsc-geo=5

Javascript don't allow sending cookies but is there anyway i could set it using something like<br>`x-Cookie: dsc-geo=5`

**Comment by tjvr** [comment]
Most CORS proxies strip user credentials (as defined in the [CORS spec](http://www.w3.org/TR/cors/#user-credentials)). I don't know of a CORS proxy that would allow this.

Sounds like a strange API. You might need a custom proxy?

**Comment by jimmywarting** [comment]
>You might need a custom proxy?

I'm afraid so

**Comment by technoboy10** [comment]
Yeah, I don't really want to allow cookies/headers to be set - seems like it might open a can of worms I don't really want to deal with. Sorry!
