### ISSUE TITLE
Cross Origin

### ISSUE THREAD

**Issue by ttechnik** [technoboy10/crossorigin.me#80]
The simple, and perfect!

var xmlHttp = new XMLHttpRequest();
    xmlHttp.open('GET', "http://CORS-Anywhere.HerokuApp.com/" + Url + req, true);

    xmlHttp.onreadystatechange = function () {
        if (xmlHttp.readyState == 4 && xmlHttp.status == 200)
            alert(Url + "\n" + xmlHttp.responseText);
            // and some .......
    };

    xmlHttp.send();

**Comment by liam4** [comment]
Aw man, crossorigin.me isn't cross origin anymore..? Not again.. /s

:tada:

**Comment by ttechnik** [comment]
Yes, but that is not working simple

**Comment by technoboy10** [comment]
I'm... not sure I understand?
