### ISSUE TITLE
Cloudflare Error: DNS points to prohibited IP

### ISSUE THREAD

**Issue by connerbw** [technoboy10/crossorigin.me#89]
I'm trying to use: https://brucelawson.github.io/manifest/

With the URL: https://www.ssense.com/

That web services uses your "crossorigin.me" and I get: **Error: DNS points to prohibited IP**

Possible reason (where example.com is SSENSE):
_"your web server is proxying requests to "www.example.com," but because Cloudflare has been activated for that DNS record, the web server is proxying those requests to a DNS record that resolves to Cloudflare IPs, resulting in cyclical requests and the "DNS points to prohibited IP" error screen with the IP of your web server's proxy IP. Web servers should be configured to resolve www.example.com to the internal NAT-ed IP, if applicable,  or the public IP of the origin web server to prevent the problem."_

Source: 
https://support.cloudflare.com/hc/en-us/articles/200171826-Why-am-I-getting-an-error-message-of-DNS-points-to-Prohibited-IP-Error-1001

Help?

**Comment by technoboy10** [comment]
Still happening?

**Comment by connerbw** [comment]
@technoboy10 Yes.

**Comment by technoboy10** [comment]
@connerbw Thanks, I'll see if I can find out what's up.

**Comment by technoboy10** [comment]
Looks like the issue is caused by accessing a site that's using CloudFlare. Further discussion will be on #92.
