### ISSUE TITLE
EU server?

### ISSUE THREAD

**Issue by jimmywarting** [technoboy10/crossorigin.me#96]
Could you maybe host a new heruko instance on a European server?
I got a geo restriction problem when it comes from US

**Comment by technoboy10** [comment]
Heroku's Terms of Service prevent me from hosting the proxy on there, and unfortunately I don't have the resources to spin up a server in the EU (my hosting provider is only in the US). I recommend you spin up your own instance on an EU server (i.e. with DigitalOcean). Sorry!
