### ISSUE TITLE
Some proxied m3u8 cannot play

### ISSUE THREAD

**Issue by beautylix** [technoboy10/crossorigin.me#99]
Data download well and the player show LIVE, but there is no video and audio.

The URL is 

`https://crossorigin.me/http://live.gslb.letv.com/gslb?stream_id=lb_mv_1300&tag=live&ext=m3u8&sign=live_tv&platid=10&splatid=1009&format=letv&expect=1`

**Comment by technoboy10** [comment]
Hi - can you please post the code you're using to request this file from the proxy?

**Comment by beautylix** [comment]
I use videojs player to player the video.

It is solved by others, the cause is that the URLs in the m3u8 files cannot be proxied,

**Comment by technoboy10** [comment]
I suspect this is due to the size restriction on files passed through the proxy.
